/*
INSERT INTO FOOTBALL_STADIUMS VALUES(1,'Урожай','Несвиж',3000);
INSERT INTO FOOTBALL_STADIUMS VALUES(2,'Шинник','Бобруйск',25000);
INSERT INTO FOOTBALL_STADIUMS VALUES(3,'Динамо','Минск',20000);
INSERT INTO FOOTBALL_STADIUMS VALUES(4,'Локомотив','Барановичи',8000);
INSERT INTO FOOTBALL_STADIUMS VALUES(5,'Трактор','Минск',15000);
commit;
*/
/*
INSERT INTO FOOTBALL_TEAMS VALUES(1,'Бобруйский Шинник','Бобруйск','Сирин Сергей',5,2,1,3,5);
INSERT INTO FOOTBALL_TEAMS VALUES(2,'Барановичский Прометей','Прометей','Агаларов Руслан',3,4,2,0,8 );
INSERT INTO FOOTBALL_TEAMS VALUES(3,'Спартак','Бобруйск','Курбан Бердыев',2,3,0,3,9);
INSERT INTO FOOTBALL_TEAMS VALUES(4,'Сборная РБ','Минск','Ренат Вилялетдинов',1,5,0,0,10);
INSERT INTO FOOTBALL_TEAMS VALUES(5,'Несвижский Урожайник','Несвиж','Франк Веркатерин',4,2,2,2,6);
INSERT INTO FOOTBALL_TEAMS VALUES(6,'Минский Динамо','Минск','Гаджи Гаджиев',6,1,4,1,3);
commit;
*/
/*
INSERT INTO FOOTBALL_PLAYERS VALUES(1,1,'Никита Андреев',23,65,'вратарь');
INSERT INTO FOOTBALL_PLAYERS VALUES(2,1,'Михаил Кизеев',21,34,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(3,1,'Сергей Лазарев',19,96,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(4,1,'Юрий Ладыгин',29,23,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(5,1,'Михаил Пононмаренко',33,64,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(6,1,'Максим Рудаков',27,2,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(7,1,'Александр Анюков',28,45,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(8,1,'Максим Карпов',25,24,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(9,1,'Вукашин Зелумба',24,46,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(10,1,'Николас Ламбертс',21,55,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(11,1,'Роберт Кристьянович',22,50,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(12,2,'Владислав Никитин',22,61,'вратарь');
INSERT INTO FOOTBALL_PLAYERS VALUES(13,2,'Аксель Ламбер',22,60,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(14,2,'Хави Гарсия',24,70,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(15,2,'Франсиско Фернандес',25,78,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(16,2,'Мигель Гомишь',26,86,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(17,2,'Вячеслав Зенгог',28,75,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(18,2,'Шиданиил Зуев',31,4,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(19,2,'Жозе Жуниор',20,84,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(20,2,'Артем Попович',23,24,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(21,2,'Константин Троянов',23,85,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(22,2,'Олег Шапов',25,63,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(23,3,'Артем Дюба',26,12,'вратарь');
INSERT INTO FOOTBALL_PLAYERS VALUES(24,3,'Игорь Шитов',27,14,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(25,3,'Александр Мартнович',24,16,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(26,3,'Тимофей Калачев',25,18,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(27,3,'Сергей Кисляк',26,20,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(28,3,'Сергей Кривец',27,22,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(29,3,'Николай Януш',22,26,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(30,3,'Сергей Корнеленко',23,28,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(31,3,'Иван Маевский',19,30,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(32,3,'Ренан Брессан',20,40,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(33,3,'Игорь Стесевич',27,43,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(34,4,'Станислав Драгун',25,11,'вратарь');
INSERT INTO FOOTBALL_PLAYERS VALUES(35,4,'Максим Володько',29,33,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(36,4,'Вадим Авергиев',32,44,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(37,4,'Алексей Козлов',23,55,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(38,4,'Александр Максименко',30,66,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(39,4,'Сергей Кесьяков',29,77,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(40,4,'Артем Ребров',28,88,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(41,4,'Владислав Сережкин',27,99,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(42,4,'Михаил Филипов',26,13,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(43,4,'Юрий Щербаков',25,15,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(44,4,'Сергей Брызгалов',24,17,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(45,5,'Владимир Гранат',23,19,'вратарь');
INSERT INTO FOOTBALL_PLAYERS VALUES(46,5,'Илья Иванов',22,21,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(47,5,'Дмитрий Канбаров',20,21,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(48,5,'Иван Костылев',19,23,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(49,5,'Илья Кутепов',21,25,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(50,5,'Денис Кутин',22,27,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(51,5,'Айдар Лисинков',24,29,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(52,5,'Александр Лихачев',26,31,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(53,5,'Евгений Макеев',28,33,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(54,5,'Артем Мамин',30,85,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(55,5,'Леонид Миронов',32,91,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(56,6,'Сергей Поршевлюк',31,92,'вратарь');
INSERT INTO FOOTBALL_PLAYERS VALUES(57,6,'Александр Пуцко',29,98,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(58,6,'Николай Рассказов',27,93,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(59,6,'Артем Сокол',25,97,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(60,6,'Николай Фадеев',23,94,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(61,6,'Иван Хомуха',21,96,'защитник');
INSERT INTO FOOTBALL_PLAYERS VALUES(62,6,'Андрей Щеголев',19,95,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(63,6,'Константин Щербаковский',25,67,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(64,6,'Джамо Ананидзе',28,57,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(65,6,'Владлен Бабай',24,47,'нападающий');
INSERT INTO FOOTBALL_PLAYERS VALUES(66,6,'Зелемхан Бакаров',21,37,'защитник');
commit;
*/
/*
INSERT INTO FOOTBALL_PLAYERS VALUES(67,Петр Володкин
INSERT INTO FOOTBALL_PLAYERS VALUES(68,Денис Глушаков
INSERT INTO FOOTBALL_PLAYERS VALUES(69,Даниил Горовых
INSERT INTO FOOTBALL_PLAYERS VALUES(,Аяз Гулиев
INSERT INTO FOOTBALL_PLAYERS VALUES(,Квинси Промес
INSERT INTO FOOTBALL_PLAYERS VALUES(,Ромуло Монтейру
INSERT INTO FOOTBALL_PLAYERS VALUES(,Зелуиш Андроде
INSERT INTO FOOTBALL_PLAYERS VALUES(,Артем Федчук
INSERT INTO FOOTBALL_PLAYERS VALUES(,Георгий Елкадзе
INSERT INTO FOOTBALL_PLAYERS VALUES(,Ивелин Попов
INSERT INTO FOOTBALL_PLAYERS VALUES(,Лоренсо Санадрия
INSERT INTO FOOTBALL_PLAYERS VALUES(,Игорь Леонтьев
INSERT INTO FOOTBALL_PLAYERS VALUES(,Илья Мазо
INSERT INTO FOOTBALL_PLAYERS VALUES(,Даниил Полубояринов
INSERT INTO FOOTBALL_PLAYERS VALUES(,Иппэй Синодзука
INSERT INTO FOOTBALL_PLAYERS VALUES(,Юрий Мофсисян
INSERT INTO FOOTBALL_PLAYERS VALUES(,Павел Яковлев
INSERT INTO FOOTBALL_PLAYERS VALUES(,Сардар Таски
INSERT INTO FOOTBALL_PLAYERS VALUES(,Кирилл Филатов
INSERT INTO FOOTBALL_PLAYERS VALUES(,Илья Сухорченко
INSERT INTO FOOTBALL_PLAYERS VALUES(,Антон Митрюшкин
INSERT INTO FOOTBALL_PLAYERS VALUES(,Леонид Миронов
INSERT INTO FOOTBALL_PLAYERS VALUES(,Алексей Папин
*/

/*
ID_MATCH
ID_TEAM_FT
ID_TEAM_SK
ID_STADIUM
COST_TICKET
DATE_MATCH
*/
INSERT INTO FOOTBALL_MATCHES VALUES(1,5,4,5,15,TO_DATE('2015/08/23 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),0,0);
INSERT INTO FOOTBALL_MATCHES VALUES(1,6,2,3,25,TO_DATE('2015/08/24 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),3,3);
INSERT INTO FOOTBALL_MATCHES VALUES(1,6,1,2,15,TO_DATE('2015/08/28 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),4,4);
INSERT INTO FOOTBALL_MATCHES VALUES(1,5,2,3,10,TO_DATE('2015/08/29 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),4,4);


INSERT INTO FOOTBALL_MATCHES VALUES(1,5,3,1,10,TO_DATE('2016/04/02 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),1,0);
INSERT INTO FOOTBALL_MATCHES VALUES(2,1,2,3,30,TO_DATE('2016/04/06 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),4,3);
INSERT INTO FOOTBALL_MATCHES VALUES(3,3,6,5,20,TO_DATE('2016/04/11 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),3,0);
INSERT INTO FOOTBALL_MATCHES VALUES(4,4,1,4,25,TO_DATE('2016/04/15 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),2,1);
INSERT INTO FOOTBALL_MATCHES VALUES(5,2,5,2,15,TO_DATE('2016/04/18 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),2,0);
INSERT INTO FOOTBALL_MATCHES VALUES(6,4,6,1,20,TO_DATE('2016/04/20 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),4,0);
INSERT INTO FOOTBALL_MATCHES VALUES(7,2,4,2,15,TO_DATE('2016/04/22 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),3,2);
INSERT INTO FOOTBALL_MATCHES VALUES(8,6,3,5,10,TO_DATE('2016/04/23 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),4,2);
INSERT INTO FOOTBALL_MATCHES VALUES(9,2,1,2,25,TO_DATE('2016/04/27 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),2,0);
INSERT INTO FOOTBALL_MATCHES VALUES(10,3,1,4,10,TO_DATE('2016/04/30 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),2,1);
INSERT INTO FOOTBALL_MATCHES VALUES(11,1,3,3,30,TO_DATE('2016/05/01 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),4,3);
INSERT INTO FOOTBALL_MATCHES VALUES(12,3,4,1,20,TO_DATE('2016/05/03 00:00:00', 'yyyy/mm/dd hh24:mi:ss'),3,1);
commit;





